if(gRPC_BUILD_IBVERBS)
message("Enable ibverbs")
find_package(ibverbs REQUIRED)
if(IBVERBS_FOUND)
    set(_gRPC_IBVERBS_INCLUDE_DIR ${IBVERBS_INCLUDE_DIRS})
    set(_gRPC_IBVERBS_LIBRARIES ${IBVERBS_LIBRARIES})
    add_definitions(-DHAVE_IBVERBS)
else()
    message(FATAL "Cannot find ibverbs.")
endif()
endif()